### ISSUE TITLE
Unable to retrieve user with ID 1

### ISSUE THREAD

**Issue by renzoepolo** [portainer/helper-reset-password#1]
I did the first boot with the --no-auth flag. Now I want to create a username and password but the administrator user was not created.
Tried deleting the container and volume but everything remains the same.
Is there a solution?

**Comment by deviantony** [comment]
@renzoepolo Deleting the container and volume should actually reset Portainer entirely and will allow you to go through the administrator user initialization process.

Make sure to clean your browser cache right after you re-create the container or access the Portainer instance via a private navigation session.

**Comment by renzoepolo** [comment]
I cleared the cache and it worked perfect. Thank you
