### ISSUE TITLE
Unable to find db on disk error

### ISSUE THREAD

**Issue by GeorgelT** [portainer/helper-reset-password#2]
Hello,

I've gone through the provided steps in the official documentation, it seems not to have worked.

Steps I went through:

1. stopped the container:
``` 
docker stop "c69cbc926fac"          
c69cbc926fac
```
2. ran the provided command which pulled an image(don't think it should have):
``` docker run --rm -v portainer_data:/data portainer/helper-reset-password
Unable to find image 'portainer/helper-reset-password:latest' locally
latest: Pulling from portainer/helper-reset-password
79916c70cb9e: Pull complete 
93e26fa95550: Pull complete 
Digest: sha256:735a809b1bfe14b5fae340d4b350bae97c2016371c47fb6e34d71a45e4512f79
Status: Downloaded newer image for portainer/helper-reset-password:latest
2021/01/10 08:47:03 Unable to locate /data/portainer.db on disk
```
3. could not reset password because got error message: **Unable to locate /data/portainer.db on disk**
4. Tried to confirm volume name with and tried again:
``` docker volume ls
DRIVER    VOLUME NAME
......
local     portainer_data

docker run --rm -v portainer_data:/data portainer/helper-reset-password
2021/01/10 08:48:01 Unable to locate /data/portainer.db on disk

```
How should I proceed from this point? Should I just reinstall or is there a solution to this? The docker image of protainer I've been using until this time is from 5 months ago, so before v.2 became a thing.

``` 
docker images
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
postgres                          latest    817f2d3d51ec   3 months ago    314MB
portainer/portainer               latest    62771b0b9b09   5 months ago    79.1MB
portainer/helper-reset-password   latest    9652765a8b26   7 months ago    6.11MB
```

If I need to reinstall the obvious next question does protainer detect the stacks it's allready created/managed?
edit: formating of code got messed up.

**Comment by deviantony** [comment]
Hey @GeorgelT, which version of Portainer are you running? Looks like an old version and we did not test it against old versions of Portainer.

Can you try to bind mount the Portainer volume in a container with a shell (like busybox) and inspect the `/data` folder? 

> ran the provided command which pulled an image (don't think it should have):

To answer that, this is normal. The helper is done provided via a Docker image.

**Comment by GeorgelT** [comment]
Hey,

I solved this problem by pulling the latest image and starting it like in official documentation.

` docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
`
The thing that stood out, looks like the image name has changed, was protainer/protainer previously, that's why I couldn't update the image previously.

It started like a new install, asked me to setup new admin password, selected that it use docker and I have all my stacks, volumes and co back.

Edit: data was persistent between host restart, so somehow the DB got corrupted dissapleared somehow when I stopped the container to recover password.

Stacks show only limited control, they are not detected as being created by protainer, is there a way to fix this or do I need to recreate them?

**Comment by deviantony** [comment]
@GeorgelT ok, glad your problem is solved, I will close this issue then.

Stacks created outside of Portainer will always be marked as limited, you'll need to re-create them inside Portainer for full control.

If you have any more questions, I'd recommend joining us on Slack via portainer.slack.com
